apiVersion: v1
kind: Service
metadata:
  name: nodejsapp
  labels:
    app: nodejsapp
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: nodejsapp
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
spec:
  selector:
    matchLabels:
      app: nodejsapp
      version: v1
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nodejsapp
        version: v1
    spec:
      #imagePullSecrets:
      #  - name: regcred
      containers:
        - name: nodejsapp
          image: edisaac/nodejsapp:c9f8dd3
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 3000
