apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  #namespace: ingress-nginx
spec:

  #loadBalancerIP: 34.148.23.97
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443 
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 34.148.23.97 #34.148.114.189        